/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.peony.iview.service;


public enum LoginType implements org.apache.thrift.TEnum {
  APP(0),
  QQ(1),
  WEIBO(2);

  private final int value;

  private LoginType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static LoginType findByValue(int value) { 
    switch (value) {
      case 0:
        return APP;
      case 1:
        return QQ;
      case 2:
        return WEIBO;
      default:
        return null;
    }
  }
}
